
package codigo;

public enum Tokens {
     PALABRA_RESERVADA,
    IDENTIFICADOR,
    NUMERO,
    OPERADOR_ASIGNACION,
    DELIMITADOR,
    PARA_IZQUIERDO,
    PARA_DERECHO,
    FIN_SENTENCIA,
    OPERADOR_ARITMETICO,
    OPERADOR_RELACIONAL,
    ERROR
}
